#FROM quay.io/wildfly/wildfly:26.0.1.Final
FROM jboss/wildfly:10.1.0.Final

USER root

EXPOSE 8080

COPY /topaz/ /opt/jboss/wildfly

RUN mkdir /opt/jboss/wildfly/standalone/log \
&& chown -R jboss:0 /opt/jboss/wildfly \
&& chmod -R g+rw /opt/jboss/wildfly \
&& chmod 777 /opt/jboss/wildfly/bin/*.sh

USER jboss
CMD ["/opt/jboss/wildfly/bin/runtopaz.sh"]